"""custom album track table

Revision ID: 0be5fed1e64f
Revises: 72412854b239
Create Date: 2026-05-10 00:56:27.178604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be5fed1e64f'
down_revision = '72412854b239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_album_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_album_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['custom_album_id'], ['custom_albums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_album_tracks')
    # ### end Alembic commands ###
