"""implementa sistema de artistas e platinas

Revision ID: 2513271bd247
Revises: f291b8be6bb6
Create Date: 2026-04-15 15:07:14.150933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2513271bd247'
down_revision = 'f291b8be6bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_platinums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('spotify_artist_id', sa.String(length=100), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('artist_image_url', sa.String(length=500), nullable=True),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spotify_artist_id', name='uix_user_artist_platinum')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_platinums')
    # ### end Alembic commands ###
