"""Add spotify tokens to user

Revision ID: 383f7d4a5879
Revises: 97eb31bca962
Create Date: 2025-12-27 11:04:16.969180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383f7d4a5879'
down_revision = '97eb31bca962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('token_expires_at', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_expires_at')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
