"""implementando streak de reviews integrada no user

Revision ID: 42813cf99f6f
Revises: 2513271bd247
Create Date: 2026-04-15 19:31:52.270887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42813cf99f6f'
down_revision = '2513271bd247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('longest_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('longest_streak')
        batch_op.drop_column('current_streak')

    # ### end Alembic commands ###
