"""add artist and album FKs on curation, platinum and review

Revision ID: 5f8d16269756
Revises: a96d03d9e57f
Create Date: 2026-05-09 20:02:00.163714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8d16269756'
down_revision = 'a96d03d9e57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album_curation_votes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'albums', ['spotify_album_id'], ['spotify_album_id'])

    with op.batch_alter_table('album_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_spotify_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('album_spotify_id_fk', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_album_reviews_album_spotify_id_fk'), ['album_spotify_id_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_album_reviews_artist_spotify_id'), ['artist_spotify_id'], unique=False)
        batch_op.create_foreign_key(None, 'albums', ['album_spotify_id_fk'], ['spotify_album_id'])
        batch_op.create_foreign_key(None, 'artists', ['artist_spotify_id'], ['spotify_artist_id'])

    with op.batch_alter_table('user_platinums', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'artists', ['spotify_artist_id'], ['spotify_artist_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_platinums', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('album_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_album_reviews_artist_spotify_id'))
        batch_op.drop_index(batch_op.f('ix_album_reviews_album_spotify_id_fk'))
        batch_op.drop_column('album_spotify_id_fk')
        batch_op.drop_column('artist_spotify_id')

    with op.batch_alter_table('album_curation_votes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
