"""custom album table

Revision ID: 72412854b239
Revises: 5f8d16269756
Create Date: 2026-05-10 00:41:19.726216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72412854b239'
down_revision = '5f8d16269756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_albums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('artist_name', sa.String(length=200), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_albums')
    # ### end Alembic commands ###
