"""initial migration

Revision ID: 97eb31bca962
Revises: 
Create Date: 2025-12-26 19:04:47.065667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97eb31bca962'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_spotify_id'), ['spotify_id'], unique=True)

    op.create_table('album_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('spotify_album_id', sa.String(length=100), nullable=False),
    sa.Column('album_name', sa.String(length=200), nullable=False),
    sa.Column('artist_name', sa.String(length=200), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('album_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_album_reviews_spotify_album_id'), ['spotify_album_id'], unique=False)

    op.create_table('track_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('album_review_id', sa.UUID(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=100), nullable=False),
    sa.Column('track_name', sa.String(length=200), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['album_review_id'], ['album_reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_review_id', 'spotify_track_id', name='unique_review_track')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_reviews')
    with op.batch_alter_table('album_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_reviews_spotify_album_id'))

    op.drop_table('album_reviews')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_spotify_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
