"""Add indexes in reviews for optimization

Revision ID: a8083a8c46f0
Revises: 383f7d4a5879
Create Date: 2025-12-27 20:13:25.648314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8083a8c46f0'
down_revision = '383f7d4a5879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album_reviews', schema=None) as batch_op:
        batch_op.alter_column('album_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('artist_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_album_reviews_spotify_album_id'))
        batch_op.create_index('idx_reviews_spotify_album', ['spotify_album_id'], unique=False)
        batch_op.create_index('idx_reviews_user_date', ['user_id', 'created_at'], unique=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('track_reviews', schema=None) as batch_op:
        batch_op.alter_column('track_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('track_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('unique_review_track'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_review_track'), ['album_review_id', 'spotify_track_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('track_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('track_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('album_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_index('idx_reviews_user_date')
        batch_op.drop_index('idx_reviews_spotify_album')
        batch_op.create_index(batch_op.f('ix_album_reviews_spotify_album_id'), ['spotify_album_id'], unique=False)
        batch_op.alter_column('tier',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
        batch_op.alter_column('artist_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('album_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
