"""add artist, album, album_track tables

Revision ID: a96d03d9e57f
Revises: 2718788f41f1
Create Date: 2026-05-09 19:55:25.589272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a96d03d9e57f'
down_revision = '2718788f41f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spotify_artist_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('genres_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artists_spotify_artist_id'), ['spotify_artist_id'], unique=True)

    op.create_table('albums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spotify_album_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('clean_name', sa.String(length=300), nullable=True),
    sa.Column('artist_name', sa.String(length=200), nullable=False),
    sa.Column('artist_spotify_id', sa.String(length=100), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('total_tracks', sa.Integer(), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_spotify_id'], ['artists.spotify_artist_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_albums_artist_spotify_id'), ['artist_spotify_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_albums_spotify_album_id'), ['spotify_album_id'], unique=True)

    op.create_table('album_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=100), nullable=False),
    sa.Column('album_spotify_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('suggested_ignore', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['album_spotify_id'], ['albums.spotify_album_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('album_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_album_tracks_album_spotify_id'), ['album_spotify_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_album_tracks_spotify_track_id'), ['spotify_track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_tracks_spotify_track_id'))
        batch_op.drop_index(batch_op.f('ix_album_tracks_album_spotify_id'))

    op.drop_table('album_tracks')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_spotify_album_id'))
        batch_op.drop_index(batch_op.f('ix_albums_artist_spotify_id'))

    op.drop_table('albums')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artists_spotify_artist_id'))

    op.drop_table('artists')
    # ### end Alembic commands ###
