"""remove fk album_curation_votes

Revision ID: bf27d65738ae
Revises: 0be5fed1e64f
Create Date: 2026-05-10 17:25:07.366698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf27d65738ae'
down_revision = '0be5fed1e64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spotify_artist_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('genres_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artists_spotify_artist_id'), ['spotify_artist_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('token_expires_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_spotify_id'), ['spotify_id'], unique=True)

    op.create_table('album_curation_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('spotify_album_id', sa.String(length=100), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spotify_album_id', name='uix_user_album_vote')
    )
    with op.batch_alter_table('album_curation_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_album_curation_votes_spotify_album_id'), ['spotify_album_id'], unique=False)

    op.create_table('albums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spotify_album_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('clean_name', sa.String(length=300), nullable=True),
    sa.Column('artist_name', sa.String(length=200), nullable=False),
    sa.Column('artist_spotify_id', sa.String(length=100), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('total_tracks', sa.Integer(), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_spotify_id'], ['artists.spotify_artist_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_albums_artist_spotify_id'), ['artist_spotify_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_albums_spotify_album_id'), ['spotify_album_id'], unique=True)

    op.create_table('blog_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('track_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_posts_slug'), ['slug'], unique=True)

    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_target_type'), ['target_type'], unique=False)

    op.create_table('custom_albums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('artist_name', sa.String(length=200), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_meta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', 'year', name='uix_user_month_year_meta')
    )
    op.create_table('user_platinums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('spotify_artist_id', sa.String(length=100), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('artist_image_url', sa.String(length=500), nullable=True),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['spotify_artist_id'], ['artists.spotify_artist_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spotify_artist_id', name='uix_user_artist_platinum')
    )
    op.create_table('votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_id', 'target_type', name='uix_user_interaction_vote')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_votes_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_target_type'), ['target_type'], unique=False)

    op.create_table('album_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('spotify_album_id', sa.String(length=100), nullable=False),
    sa.Column('album_name', sa.String(length=255), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('artist_genres', sa.JSON(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('artist_spotify_id', sa.String(length=100), nullable=True),
    sa.Column('album_spotify_id_fk', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['album_spotify_id_fk'], ['albums.spotify_album_id'], ),
    sa.ForeignKeyConstraint(['artist_spotify_id'], ['artists.spotify_artist_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('album_reviews', schema=None) as batch_op:
        batch_op.create_index('idx_reviews_spotify_album', ['spotify_album_id'], unique=False)
        batch_op.create_index('idx_reviews_user_date', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_album_reviews_album_spotify_id_fk'), ['album_spotify_id_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_album_reviews_artist_spotify_id'), ['artist_spotify_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_album_reviews_spotify_album_id'), ['spotify_album_id'], unique=False)

    op.create_table('album_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=100), nullable=False),
    sa.Column('album_spotify_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('suggested_ignore', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['album_spotify_id'], ['albums.spotify_album_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('album_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_album_tracks_album_spotify_id'), ['album_spotify_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_album_tracks_spotify_track_id'), ['spotify_track_id'], unique=False)

    op.create_table('blog_post_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post_mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_mentions_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_mentions_target_type'), ['target_type'], unique=False)

    op.create_table('custom_album_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_album_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['custom_album_id'], ['custom_albums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('album_review_id', sa.UUID(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=100), nullable=True),
    sa.Column('track_name', sa.String(length=255), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_ignored', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['album_review_id'], ['album_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_reviews')
    op.drop_table('custom_album_tracks')
    with op.batch_alter_table('blog_post_mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_mentions_target_type'))
        batch_op.drop_index(batch_op.f('ix_blog_post_mentions_target_id'))

    op.drop_table('blog_post_mentions')
    with op.batch_alter_table('album_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_tracks_spotify_track_id'))
        batch_op.drop_index(batch_op.f('ix_album_tracks_album_spotify_id'))

    op.drop_table('album_tracks')
    with op.batch_alter_table('album_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_reviews_spotify_album_id'))
        batch_op.drop_index(batch_op.f('ix_album_reviews_artist_spotify_id'))
        batch_op.drop_index(batch_op.f('ix_album_reviews_album_spotify_id_fk'))
        batch_op.drop_index('idx_reviews_user_date')
        batch_op.drop_index('idx_reviews_spotify_album')

    op.drop_table('album_reviews')
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_target_type'))
        batch_op.drop_index(batch_op.f('ix_votes_target_id'))

    op.drop_table('votes')
    op.drop_table('user_platinums')
    op.drop_table('monthly_meta')
    op.drop_table('custom_albums')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_target_type'))
        batch_op.drop_index(batch_op.f('ix_comments_target_id'))

    op.drop_table('comments')
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_slug'))

    op.drop_table('blog_posts')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_spotify_album_id'))
        batch_op.drop_index(batch_op.f('ix_albums_artist_spotify_id'))

    op.drop_table('albums')
    with op.batch_alter_table('album_curation_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_curation_votes_spotify_album_id'))

    op.drop_table('album_curation_votes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_spotify_id'))

    op.drop_table('users')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artists_spotify_artist_id'))

    op.drop_table('artists')
    # ### end Alembic commands ###
