"""implementa sistema de curadoria e faixas ignoradas

Revision ID: f291b8be6bb6
Revises: b80a86b0ebc3
Create Date: 2026-04-15 11:54:35.740909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f291b8be6bb6'
down_revision = 'b80a86b0ebc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_curation_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('spotify_album_id', sa.String(length=100), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spotify_album_id', name='uix_user_album_vote')
    )
    with op.batch_alter_table('album_curation_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_album_curation_votes_spotify_album_id'), ['spotify_album_id'], unique=False)

    with op.batch_alter_table('track_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ignored', sa.Boolean(), nullable=False))
        batch_op.alter_column('score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_reviews', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('is_ignored')

    with op.batch_alter_table('album_curation_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_curation_votes_spotify_album_id'))

    op.drop_table('album_curation_votes')
    # ### end Alembic commands ###
